#### Entender solicitud de Lac

* Equipo aquí con las líneas que la gerencia quiere ver las demás las ocultamos, así mismo debemos completar 2024 y años anteriores que si tenemos.

* @Mayra Vera Melendez @Andrea Aguirre Zevallos como podemos hacer para que la data de Mkt digital este en el Sperant, respuesta mañana a mas tardar

* @Diego Ricardo Di Natale Rios @Andrea Aguirre Zevallos y @Johny Segura Ydiaquez  toda la Info sale del Sperant, excepto las primeras líneas de mkt, como podemos hacer para que la hagamos automatizada, tal vez un dashboard junto con los enlaces externos.

* Nos juntamos para explicarles como generamos la información, @Diego Ricardo Di Natale Rios ayuda con la agenda de ser posible hoy.

In [22]:
import pandas as pd
print('Librerías')

Librerías

In [2]:
path = 'data/Funnel Integral Comas y Proyecto May25.xlsx'
df =pd.read_excel(path)

c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

In [24]:
adjunto = pd.read_excel(path, sheet_name=None)
for car, cont in adjunto.items():
    print(f"Sheet: {car}")
    print(cont.shape)  # Display shape
    #print(cont.head())  # Display the first few rows of each sheet

Sheet: CLUB RESIDENCIAL COMAS
(39, 36)
Sheet: VILLA 55
(38, 11)
Sheet: VILLA 60
(38, 11)
Sheet: GERANIOS
(37, 4)
Sheet: BREÑA
(37, 4)
Sheet: CALLAO
(37, 4)
Sheet: PDM
(37, 4)

c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

### Línea por línea

In [46]:
import pandas as pd

def cargar_hojas_por_palabra(ruta_archivo: str) -> dict:
    """
    Lee todas las hojas de un archivo Excel y devuelve un dict
    donde la clave es la primera palabra del nombre de la hoja
    y el valor es el DataFrame correspondiente.
    """
    # lee todas las hojas en un dict {nombre_hoja: df}
    hojas = pd.read_excel(ruta_archivo, sheet_name=None)
    resultado = {}
    for nombre_hoja, df in hojas.items():
        # extrae la primera palabra (antes de espacios)
        clave = nombre_hoja.split()[0]
        # guarda copia del df bajo esa clave
        resultado[clave] = df.copy()
    return resultado

# Ejemplo de uso:
if __name__ == "__main__":
    ruta = path
    dfs = cargar_hojas_por_palabra(ruta)
    for clave, df in dfs.items():
        print(f"{clave}: {df.shape[0]} filas, {df.shape[1]} columnas")

CLUB: 39 filas, 36 columnas
VILLA: 38 filas, 11 columnas
GERANIOS: 37 filas, 4 columnas
BREÑA: 37 filas, 4 columnas
CALLAO: 37 filas, 4 columnas
PDM: 37 filas, 4 columnas

c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

In [45]:
for clave, df in dfs.items():
    df.to_excel(f"{clave}.xlsx", index=False)

In [ ]:
df.head(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3
0,PARQUES DEL MAR,NaN,NaN,NaN
1,NaN,CLUB RESIDENCIAL \nPromedio Ene-Mar 25,CLUB RESIDENCIAL \nABRIL 2025,CLUB RESIDENCIAL \nMAYO 2025
2,IMPRESIONES,2074176,2118592,2907288.5
3,ALCANCE,600335,855849,1283493
4,LEADS,521,672,445

In [36]:
df_breña = dfs['BREÑA']
df_breña.columns = df_breña.iloc[1]
df_breña = df_breña[2:]  # Elimina las dos primeras filas
df_breña.rename(columns={df_breña.columns[0]: 'MÉTRICAS'}, inplace=True)  # Renombra la primera columna
#df_breña.iloc[1]
df_breña

C:\Users\diego.dinatale\AppData\Local\Temp\ipykernel_23328\2733398809.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_breña.rename(columns={df_breña.columns[0]: 'MÉTRICAS'}, inplace=True)  # Renombra la primera columna

1,MÉTRICAS,CLUB RESIDENCIAL \nPromedio Ene-Mar 25,CLUB RESIDENCIAL \nABRIL 2025,CLUB RESIDENCIAL \nMAYO 2025
2,IMPRESIONES,2822047,3077443,2531501.5
3,ALCANCE,892491,1194632,1163122
4,LEADS,1687,1352,1340
5,INVERSIÓN,2475,2439,1945.89
6,COSTO POR LEAD,1.467101,1.803994,1.452157
7,COSTO DE ADQUISICIÓN,185.671418,243.9,216.21
8,VISITAS TOTALES,203.66,121,76
9,VISITAS PRESENCIALES,130.33,80,48
10,VISITAS VIRTUALES,73.33,41,28
11,EVALUADOS x BCO.,39.66,36,23
12,PRE CALIFICADOS x BCO,14,36,7
13,PRE CALIFICADOS x CH DIRECTO,5,18,3
14,PRE CALIFICADOS x PLAN AHORRO,9,18,4
15,SEPARACIONES BRUTAS TOTALES,13.33,10,9
16,SEPARACIONES CH DIRECTO O CONTADO,6,3,3
17,SEPARACIONES PLAN AHORRO,7.33,7,6
18,% Penetración VIVA SB/Visitas Presenciales,0.102279,0.125,0.1875
19,% Atenciones Banco/Visitas Presenciales,0.304304,0.45,0.479167
20,% Penetración Banco PreCalificados/Evaluados,0.353001,1,0.304348
21,Precio Promedio Vendido,288477.28,292144.2,285273.444
22,Metraje Promedio (Dpto. Tipico),64.389,64.53,64.067
23,Precio Promedio Vendido m2 (Dpto. típico),4480.226126,4527.261739,4452.736104
24,BBP,NaN,NaN,NaN
25,BMS,NaN,NaN,NaN
26,Bono Integrador,NaN,NaN,NaN
27,RangoTasa Minima p/Cálculo,NaN,NaN,NaN
28,"Cuota (dobles, 300 meses)",NaN,NaN,NaN
29,Ingreso Bruto Requerido (0.7),NaN,NaN,NaN
30,Caídas,2.5,0,3
31,SEPARACIONES NETAS TOTALES,10.83,10,6
32,% Caídas,0.187547,0,0.333333
33,Visitas que migraron y reservaron en otro proy...,NaN,NaN,NaN
34,Relación entre Dptos vendidos c/estac.,5/28,2/10,3/9
35,Stock de Departamentos,53,43,36
36,Stock Estacionamientos,NaN,NaN,NaN

In [3]:
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35
0,CLUB RESIDENCIAL - COMAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,CLUB RESIDENCIAL \nPromedio 2022,CLUB RESIDENCIAL \nPromedio 2023,CLUB RESIDENCIAL \nEne-23,CLUB RESIDENCIAL \nFeb-23,CLUB RESIDENCIAL \nMar-23,CLUB RESIDENCIAL \nAbr-23,CLUB RESIDENCIAL \nMay-23,CLUB RESIDENCIAL \nJun-23,CLUB RESIDENCIAL \nJul-23,...,NaN,NaN,CLUB RESIDENCIAL \nPromedio 2024,CLUB RESIDENCIAL \nPromedio Ene-Mar 25,CLUB RESIDENCIAL \nABRIL 2025,CLUB RESIDENCIAL al 26 MAYO 2025,NaN,NaN,NaN,NaN
2,IMPRESIONES,608459,981611,715768,402966,667358,1229758,743514,722817,877297,...,NaN,NaN,1685339.291667,1835857,1548174,1811016,NaN,NaN,NaN,NaN
3,ALCANCE,255229.5,379498,318835,169664,241497,402449,275879,208739,314431,...,NaN,NaN,673396,569733,761865,905624,NaN,NaN,NaN,NaN
4,LEADS,1813.416667,1329,1509,1308,1441,1011,910,934,833,...,NaN,NaN,1780,1102,1466,1082,NaN,NaN,NaN,NaN
5,INVERSIÓN,1560.788333,"$1,715",1032.6,1229,1687,2305,2260,1547,1657,...,NaN,NaN,2007.9725,2068,2296,1728,NaN,NaN,NaN,NaN
6,COSTO POR LEAD,0.860689,$1.43,0.684294,0.939602,1.170715,2.279921,2.483516,1.656317,1.989196,...,NaN,NaN,1.198542,1.876588,1.566166,1.597043,NaN,NaN,NaN,NaN
7,COSTO DE ADQUISICIÓN,60.030321,$88,46.936364,81.933333,67.48,88.653846,141.25,73.666667,75.318182,...,NaN,NaN,126.788349,110.825295,164,172.8,NaN,NaN,NaN,NaN
8,VISITAS TOTALES,652,481.545455,422,363,405,428,514,543,513,...,NaN,NaN,537,550.33,449,308,NaN,NaN,NaN,NaN
9,VISITAS PRESENCIALES,316,323.818182,374,318,324,310,363,318,389,...,NaN,NaN,307.25,323.33,268,189,NaN,NaN,NaN,NaN
10,VISITAS VIRTUALES,336,157.727273,48,45,81,118,151,225,124,...,NaN,NaN,229.75,227,181,119,NaN,NaN,NaN,NaN
11,EVALUADOS x BCO.,287,232.090909,187,224,248,231,331,366,315,...,NaN,NaN,103.25,222.33,199,154,NaN,NaN,NaN,NaN
12,PRE CALIFICADOS x BCO,157,112.454545,97,113,143,112,154,183,141,...,NaN,NaN,54,98.66,126,96,NaN,NaN,NaN,NaN
13,PRE CALIFICADOS x CH DIRECTO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,37.5,69.66,104,75,NaN,NaN,NaN,NaN
14,PRE CALIFICADOS x PLAN AHORRO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,16.5,29,22,21,NaN,NaN,NaN,NaN
15,SEPARACIONES BRUTAS TOTALES,26,20.818182,22,15,25,26,16,21,22,...,NaN,NaN,16,18.66,14,10,NaN,Motivo de no compra pre calificados - Mayo,Cant.,%
16,SEPARACIONES CH DIRECTO O CONTADO,NaN,10.636364,14,11,15,17,7,7,9,...,NaN,NaN,13.25,12.33,9,7,NaN,Mal reportado,1,0.008333
17,SEPARACIONES PLAN AHORRO,NaN,10.181818,8,4,10,9,9,14,13,...,NaN,NaN,2.75,6.33,5,3,NaN,Sólo información,55,0.458333
18,% Penetración VIVA SB/Visitas Presenciales,0.082278,0.06429,0.058824,0.04717,0.07716,0.083871,0.044077,0.066038,0.056555,...,NaN,NaN,0.052075,0.057712,0.052239,0.05291,NaN,Evaluando,64,0.533333
19,% Atenciones Banco/Visitas Presenciales,0.908228,0.716732,0.5,0.704403,0.765432,0.745161,0.911846,1.150943,0.809769,...,NaN,NaN,0.336046,0.687626,0.742537,0.814815,NaN,Total,120,1
20,% Penetración Banco PreCalificados/Evaluados,0.547038,0.484528,0.518717,0.504464,0.576613,0.484848,0.465257,0.5,0.447619,...,NaN,NaN,0.523002,0.443755,0.633166,0.623377,NaN,NaN,NaN,NaN
21,Precio Promedio Vendido,245628,243391,232131,236530,236317,242481,242815,249727,246882,...,NaN,NaN,255197.6,259685.71,260957,248570,NaN,NaN,NaN,NaN
22,Metraje Promedio (Dpto. Tipico),73,69.1,69.68,68.62,71.97,69.56,68.57,69.85,69.1,...,NaN,NaN,70.707812,70.89,75.607,70.27,NaN,NaN,NaN,NaN
23,Precio Promedio Vendido m2 (Dpto. típico),3364.767123,3522.301013,3331.386338,3446.954241,3283.548701,3485.925819,3541.125857,3575.189692,3572.821997,...,NaN,NaN,3609.185336,3663.220624,3451.492587,3537.355913,NaN,NaN,NaN,NaN
24,BBP,10800,7300,10800,10800,10800,10800,10800,10800,7300,...,NaN,NaN,7300,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,BMS,5400,5400,5400,5400,5400,5400,5400,5400,5400,...,NaN,NaN,5400,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Bono Integrador,-,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,RangoTasa Minima p/Cálculo,0.0882,0.0904,0.0937,0.086,0.0879,0.0854,0.0854,0.0854,0.086,...,NaN,NaN,0.0904,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,"Cuota (dobles, 300 meses)",1567,1535,1447,1485,1505,1517,1520,1565,1577,...,NaN,NaN,1535,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Ingreso Bruto Requerido (0.7),4398,4400,4087,4254,4286,4365,4398,4870,4412,...,NaN,NaN,4400,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Caídas,10,8.454545,8,1,18,10,10,7,8,...,NaN,NaN,8.75,6.33,7,5,NaN,NaN,NaN,NaN
31,SEPARACIONES NETAS TOTALES,16,12.363636,14,14,7,16,6,14,14,...,NaN,NaN,7.25,12.33,7,5,NaN,NaN,NaN,NaN
32,% Caídas,0.384615,0.406114,0.363636,0.066667,0.72,0.384615,0.625,0.333333,0.363636,...,NaN,NaN,0.546875,0.339228,0.5,0.5,NaN,NaN,NaN,NaN
33,Visitas que migraron y reservaron en otro proy...,14,6.818182,4,8,15,9,7,6,8,...,NaN,NaN,6.818182,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Relación entre Dptos vendidos c/estac.,114/316,50/244,5/22,5/15,6/25,5/26,1/16,1/21,4/22,...,NaN,NaN,50/244,3.3/18.6,5/14,3/10,NaN,NaN,NaN,NaN
35,Stock de Departamentos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,16,154,148,NaN,NaN,NaN,NaN
36,Stock Estacionamientos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Oculta

In [37]:
from typing import Dict, List, Tuple
import pandas as pd
from openpyxl import load_workbook

class ExcelLoader:
    def __init__(self, filepath: str):
        """
        Inicializa el loader con la ruta del archivo.
        """
        self.filepath = filepath
        # Cargamos el workbook una sola vez
        self._wb = load_workbook(filepath, data_only=True)
    
    def _hidden_dims(self, sheet_name: str) -> Tuple[List[int], List[str]]:
        """
        Devuelve (filas_ocultas, cols_ocultas) de la hoja dada.
        - filas_ocultas: lista de índices Excel (1-based)
        - cols_ocultas: lista de letras de columna
        """
        ws = self._wb[sheet_name]
        filas = [r for r, dim in ws.row_dimensions.items() if dim.hidden]
        cols  = [c for c, dim in ws.column_dimensions.items() if dim.hidden]
        return filas, cols
    
    def load_sheets_by_prefix(self) -> Dict[str, pd.DataFrame]:
        """
        Lee todas las hojas, elimina filas/columnas ocultas
        y las agrupa en un dict bajo la primera palabra de su nombre.
        """
        # lee todos los dfs con pandas
        all_sheets = pd.read_excel(self.filepath, sheet_name=None)
        result: Dict[str, pd.DataFrame] = {}
        
        for sheet_name, df in all_sheets.items():
            filas_ocultas, cols_ocultas = self._hidden_dims(sheet_name)
            
            # Drop hidden rows (ajustamos a 0-based)
            if filas_ocultas:
                df = df.drop(index=[r - 1 for r in filas_ocultas], errors="ignore")
            # Drop hidden columns
            if cols_ocultas:
                df = df.drop(columns=cols_ocultas, errors="ignore")
            
            key = sheet_name.split()[0]
            result[key] = df.reset_index(drop=True)
        
        return result

In [38]:

# Ejemplo de uso
if __name__ == "__main__":
    loader = ExcelLoader(path)
    dfs = loader.load_sheets_by_prefix()
    for prefix, df in dfs.items():
        print(f"{prefix}: {df.shape[0]} filas × {df.shape[1]} columnas")

CLUB: 29 filas × 36 columnas
VILLA: 31 filas × 11 columnas
GERANIOS: 16 filas × 4 columnas
BREÑA: 17 filas × 4 columnas
CALLAO: 16 filas × 4 columnas
PDM: 30 filas × 4 columnas

c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

In [ ]:
df_breña = dfs['BREÑA']
df_breña.columns = df_breña.iloc[1]
df_breña = df_breña[2:]  # Elimina las dos primeras filas
df_breña.rename(columns={df_breña.columns[0]: 'MÉTRICAS'}, inplace=True)  # Renombra la primera columna
df_breña

C:\Users\diego.dinatale\AppData\Local\Temp\ipykernel_23328\2733398809.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_breña.rename(columns={df_breña.columns[0]: 'MÉTRICAS'}, inplace=True)  # Renombra la primera columna

1,MÉTRICAS,CLUB RESIDENCIAL \nPromedio Ene-Mar 25,CLUB RESIDENCIAL \nABRIL 2025,CLUB RESIDENCIAL \nMAYO 2025
2,IMPRESIONES,2822047,3077443,2531501.5
3,ALCANCE,892491,1194632,1163122
4,LEADS,1687,1352,1340
5,INVERSIÓN,2475,2439,1945.89
6,COSTO POR LEAD,1.467101,1.803994,1.452157
7,COSTO DE ADQUISICIÓN,185.671418,243.9,216.21
8,VISITAS TOTALES,203.66,121,76
9,VISITAS PRESENCIALES,130.33,80,48
10,VISITAS VIRTUALES,73.33,41,28
11,EVALUADOS x BCO.,39.66,36,23
12,PRE CALIFICADOS x BCO,14,36,7
13,PRE CALIFICADOS x CH DIRECTO,5,18,3
14,PRE CALIFICADOS x PLAN AHORRO,9,18,4
15,SEPARACIONES BRUTAS TOTALES,13.33,10,9
16,SEPARACIONES CH DIRECTO O CONTADO,6,3,3
17,SEPARACIONES PLAN AHORRO,7.33,7,6
18,% Penetración VIVA SB/Visitas Presenciales,0.102279,0.125,0.1875
19,% Atenciones Banco/Visitas Presenciales,0.304304,0.45,0.479167
20,% Penetración Banco PreCalificados/Evaluados,0.353001,1,0.304348
21,Precio Promedio Vendido,288477.28,292144.2,285273.444
22,Metraje Promedio (Dpto. Tipico),64.389,64.53,64.067
23,Precio Promedio Vendido m2 (Dpto. típico),4480.226126,4527.261739,4452.736104
24,BBP,NaN,NaN,NaN
25,BMS,NaN,NaN,NaN
26,Bono Integrador,NaN,NaN,NaN
27,RangoTasa Minima p/Cálculo,NaN,NaN,NaN
28,"Cuota (dobles, 300 meses)",NaN,NaN,NaN
29,Ingreso Bruto Requerido (0.7),NaN,NaN,NaN
30,Caídas,2.5,0,3
31,SEPARACIONES NETAS TOTALES,10.83,10,6
32,% Caídas,0.187547,0,0.333333
33,Visitas que migraron y reservaron en otro proy...,NaN,NaN,NaN
34,Relación entre Dptos vendidos c/estac.,5/28,2/10,3/9
35,Stock de Departamentos,53,43,36
36,Stock Estacionamientos,NaN,NaN,NaN

### Leyendo df con filas y col ocultas

In [55]:
from typing import Dict, List, Tuple
import pandas as pd
from openpyxl import load_workbook

class ExcelLoader:
    def __init__(self, filepath: str):
        """
        Inicializa el loader con la ruta del archivo.
        """
        self.filepath = filepath
        self._wb = load_workbook(filepath, data_only=True)
    
    def _hidden_dims(self, sheet_name: str) -> Tuple[List[int], List[str]]:
        """
        Devuelve (filas_ocultas, cols_ocultas) de la hoja dada.
        - filas_ocultas: lista de índices Excel (1-based)
        - cols_ocultas: lista de letras de columna
        """
        ws = self._wb[sheet_name]
        filas = [r for r, dim in ws.row_dimensions.items() if dim.hidden]
        cols  = [c for c, dim in ws.column_dimensions.items() if dim.hidden]
        return filas, cols
    
    def load_sheets_by_prefix(self) -> Dict[str, pd.DataFrame]:
        """
        Lee todas las hojas, elimina filas/columnas ocultas,
        ajusta encabezados y renombra la primera columna a "MÉTRICAS",
        y las agrupa en un dict bajo la primera palabra de su nombre.
        """
        # lee todos los dfs con pandas
        all_sheets = pd.read_excel(self.filepath, sheet_name=None, header=None)
        result: Dict[str, pd.DataFrame] = {}
        
        for sheet_name, df in all_sheets.items():
            # 1) Elimina filas/columnas ocultas
            filas_ocultas, cols_ocultas = self._hidden_dims(sheet_name)
            if filas_ocultas:
                df = df.drop(index=[r - 1 for r in filas_ocultas], errors="ignore")
            if cols_ocultas:
                df = df.drop(columns=cols_ocultas, errors="ignore")
            
            # 2) Ajuste de encabezados: usar la fila 1 (segunda) como names
            df.columns = df.iloc[1]
            # 3) Eliminar las dos primeras filas (0 y 1)
            df = df.iloc[2:]#.reset_index(drop=True)
            # 4) Renombrar la primera columna a "MÉTRICAS"
            #first_col = 
            df.rename(columns={df.columns[0]: "MÉTRICAS"}, inplace=True)
            
            # 5) Guardar bajo la clave de la primera palabra
            key = sheet_name.split()[0]
            result[key] = df
        
        return result

# Ejemplo de uso
if __name__ == "__main__":
    loader = ExcelLoader(path)
    dfs = loader.load_sheets_by_prefix()
    for prefix, df in dfs.items():
        print(f"{prefix}: {df.shape[0]} filas × {df.shape[1]} columnas")
        display(df.head())  # si estás en Jupyter, para ver un vistazo

CLUB: 28 filas × 36 columnas

c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\diego.dinatale\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

1,MÉTRICAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,CLUB RESIDENCIAL \nPromedio 2022,CLUB RESIDENCIAL \nPromedio 2023,CLUB RESIDENCIAL \nEne-23,CLUB RESIDENCIAL \nFeb-23,CLUB RESIDENCIAL \nMar-23,CLUB RESIDENCIAL \nAbr-23,CLUB RESIDENCIAL \nMay-23,CLUB RESIDENCIAL \nJun-23,CLUB RESIDENCIAL \nJul-23,...,NaN,NaN,CLUB RESIDENCIAL \nPromedio 2024,CLUB RESIDENCIAL \nPromedio Ene-Mar 25,CLUB RESIDENCIAL \nABRIL 2025,CLUB RESIDENCIAL al 26 MAYO 2025,NaN,NaN,NaN,NaN
3,IMPRESIONES,608459,981611,715768,402966,667358,1229758,743514,722817,877297,...,NaN,NaN,1685339.291667,1835857,1548174,1811016,NaN,NaN,NaN,NaN
4,ALCANCE,255229.5,379498,318835,169664,241497,402449,275879,208739,314431,...,NaN,NaN,673396,569733,761865,905624,NaN,NaN,NaN,NaN
5,LEADS,1813.416667,1329,1509,1308,1441,1011,910,934,833,...,NaN,NaN,1780,1102,1466,1082,NaN,NaN,NaN,NaN
6,INVERSIÓN,1560.788333,"$1,715",1032.6,1229,1687,2305,2260,1547,1657,...,NaN,NaN,2007.9725,2068,2296,1728,NaN,NaN,NaN,NaN

VILLA: 29 filas × 11 columnas

1,MÉTRICAS,MÉTRICAS,MÉTRICAS,MÉTRICAS,MÉTRICAS,MÉTRICAS,MÉTRICAS,MÉTRICAS,MÉTRICAS,MÉTRICAS,MÉTRICAS
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,VILLAS 60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,ACACIA 6\nENERO 24,ACACIA 6\nFEBRERO 24,ACACIA 6\nMARZO 24,ACACIA 6\nABRIL 24,ACACIA 6\nMAYO 24,ACACIA 6\nJUNIO 24,ACACIA 6\nJULIO 24,ACACIA 60\nPromedio Ene-Mar 25,ACACIA 60\nABRIL 2025,ACACIA 60\nMAYO 2025
5,IMPRESIONES,1289267,1517418.1,1490436.733333,1575913.166667,1323850.5,1144408,1334899.5,1129047,1234118,1414070
6,ALCANCE,473221,522425.2,551391.466667,582303,595773,490174,598148.5,392422,504845.5,843995

GERANIOS: 14 filas × 4 columnas

1,MÉTRICAS,NaN,NaN,NaN
2,NaN,CLUB RESIDENCIAL \nPromedio Ene-Mar 25,CLUB RESIDENCIAL \nABRIL 2025,CLUB RESIDENCIAL \nMAYO 2025
3,IMPRESIONES,1662430,2097564,1538325.5
4,ALCANCE,491153,860578,768644
5,LEADS,3039,4392,2400
10,VISITAS PRESENCIALES,310.66,221,212

BREÑA: 15 filas × 4 columnas

1,MÉTRICAS,NaN,NaN,NaN
2,NaN,CLUB RESIDENCIAL \nPromedio Ene-Mar 25,CLUB RESIDENCIAL \nABRIL 2025,CLUB RESIDENCIAL \nMAYO 2025
3,IMPRESIONES,2822047,3077443,2531501.5
4,ALCANCE,892491,1194632,1163122
5,LEADS,1687,1352,1340
10,VISITAS PRESENCIALES,130.33,80,48

CALLAO: 14 filas × 4 columnas

1,MÉTRICAS,NaN,NaN,NaN
2,NaN,CLUB RESIDENCIAL \nPromedio Ene-Mar 25,CLUB RESIDENCIAL \nABRIL 2025,CLUB RESIDENCIAL \nMAYO 2025
3,IMPRESIONES,1949339,2431707,1681284.5
4,ALCANCE,580098,897279,626901
5,LEADS,1191,1335,897
10,VISITAS PRESENCIALES,83.33,91,75

PDM: 28 filas × 4 columnas

1,MÉTRICAS,NaN,NaN,NaN
2,NaN,CLUB RESIDENCIAL \nPromedio Ene-Mar 25,CLUB RESIDENCIAL \nABRIL 2025,CLUB RESIDENCIAL \nMAYO 2025
3,IMPRESIONES,2074176,2118592,2907288.5
4,ALCANCE,600335,855849,1283493
5,LEADS,521,672,445
6,INVERSIÓN,2918,2795,2160.93

In [48]:
dfs

{'CLUB':                                            Unnamed: 0  \
 0                            CLUB RESIDENCIAL - COMAS
 1                                                 NaN
 2                                         IMPRESIONES
 3                                             ALCANCE
 4                                               LEADS
 5                                           INVERSIÓN
 6                                      COSTO POR LEAD
 7                                COSTO DE ADQUISICIÓN
 8                                     VISITAS TOTALES
 9                                VISITAS PRESENCIALES
 10                                  VISITAS VIRTUALES
 11                                   EVALUADOS x BCO.
 12                              PRE CALIFICADOS x BCO
 13                      PRE CALIFICADOS x CH DIRECTO
 14                      PRE CALIFICADOS x PLAN AHORRO
 15                        SEPARACIONES BRUTAS TOTALES
 16                  SEPARACIONES CH DIRECTO O CONTADO
 17                           SEPARACIONES PLAN AHORRO
 18         % Penetración VIVA SB/Visitas Presenciales
 19            % Atenciones Banco/Visitas Presenciales
 20       % Penetración Banco PreCalificados/Evaluados
 21                            Precio Promedio Vendido
 22                    Metraje Promedio (Dpto. Tipico)
 23          Precio Promedio Vendido m2 (Dpto. típico)
 24                                                BBP
 25                                                BMS
 26                                    Bono Integrador
 27                         RangoTasa Minima p/Cálculo
 28                          Cuota (dobles, 300 meses)
 29                      Ingreso Bruto Requerido (0.7)
 30                                            Caídas
 31                         SEPARACIONES NETAS TOTALES
 32                                           % Caídas
 33  Visitas que migraron y reservaron en otro proy...
 34             Relación entre Dptos vendidos c/estac.
 35                             Stock de Departamentos
 36                             Stock Estacionamientos
 37                                                NaN
 38                                                NaN

                           Unnamed: 1                        Unnamed: 2  \
 0                                NaN                               NaN
 1   CLUB RESIDENCIAL \nPromedio 2022  CLUB RESIDENCIAL \nPromedio 2023
 2                             608459                            981611
 3                           255229.5                            379498
 4                        1813.416667                              1329
 5                        1560.788333                            $1,715
 6                           0.860689                             $1.43
 7                          60.030321                               $88
 8                                652                        481.545455
 9                                316                        323.818182
 10                               336                        157.727273
 11                               287                        232.090909
 12                               157                        112.454545
 13                               NaN                               NaN
 14                               NaN                               NaN
 15                                26                         20.818182
 16                               NaN                         10.636364
 17                               NaN                         10.181818
 18                          0.082278                           0.06429
 19                          0.908228                          0.716732
 20                          0.547038                          0.484528
 21                            245628                            243391
 22                                73                              69.1
 23                       3364.767123                       3522.301013
 24                             10800                              7300
 25                              5400                              5400
 26                                 -                                 -
 27                            0.0882                            0.0904
 28                              1567                              1535
 29                              4398                              4400
 30                                10                          8.454545
 31                                16                         12.363636
 32                          0.384615                          0.406114
 33                                14                          6.818182
 34                           114/316                            50/244
 35                               NaN                               NaN
 36                               NaN                               NaN
 37                               NaN                               NaN
 38                               NaN                               NaN

                    Unnamed: 3                 Unnamed: 4  \
 0                         NaN                        NaN
 1   CLUB RESIDENCIAL \nEne-23  CLUB RESIDENCIAL \nFeb-23
 2                      715768                     402966
 3                      318835                     169664
 4                        1509                       1308
 5                      1032.6                       1229
 6                    0.684294                   0.939602
 7                   46.936364                  81.933333
 8                         422                        363
 9                         374                        318
 10                         48                         45
 11                        187                        224
 12                         97                        113
 13                        NaN                        NaN
 14                        NaN                        NaN
 15                         22                         15
 16                         14                         11
 17                          8                          4
 18                   0.058824                    0.04717
 19                        0.5                   0.704403
 20                   0.518717                   0.504464
 21                     232131                     236530
 22                      69.68                      68.62
 23                3331.386338                3446.954241
 24                      10800                      10800
 25                       5400                       5400
 26                        NaN                        NaN
 27                     0.0937                      0.086
 28                       1447                       1485
 29                       4087                       4254
 30                          8                          1
 31                         14                         14
 32                   0.363636                   0.066667
 33                          4                          8
 34                       5/22                       5/15
 35                        NaN                        NaN
 36                        NaN                        NaN
 37                        NaN                        NaN
 38                        NaN                        NaN

                    Unnamed: 5                 Unnamed: 6  \
 0                         NaN                        NaN
 1   CLUB RESIDENCIAL \nMar-23  CLUB RESIDENCIAL \nAbr-23
 2                      667358                    1229758
 3                      241497                     402449
 4                        1441                       1011
 5                        1687                       2305
 6                    1.170715                   2.279921
 7                       67.48                  88.653846
 8                         405                        428
 9                         324                        310
 10                         81                        118
 11                        248                        231
 12                        143                        112
 13                        NaN                        NaN
 14                        NaN                        NaN
 15                         25                         26
 16                         15                         17
 17                         10                          9
 18                    0.07716                   0.083871
 19                   0.765432                   0.745161
 20                   0.576613                   0.484848
 21                     236317                     242481
 22                      71.97                      69.56
 23                3283.548701                3485.925819
 24                      10800                      10800
 25                       5400                       5400
 26                        NaN                        NaN
 27                     0.0879                     0.0854
 28                       1505                       1517
 29                       4286                       4365
 30                         18                         10
 31                          7                         16
 32                       0.72                   0.384615
 33                         15                          9
 34                       6/25                       5/26
 35                        NaN                        NaN
 36                        NaN                        NaN
 37                        NaN                        NaN
 38                        NaN                        NaN

                    Unnamed: 7                 Unnamed: 8  \
 0                         NaN                        NaN
 1   CLUB RESIDENCIAL \nMay-23  CLUB RESIDENCIAL \nJun-23
 2                      743514                     722817
 3                      275879                     208739
 4                         910                        934
 5                        2260                       1547
 6                    2.483516                   1.656317
 7                      141.25                  73.666667
 8                         514                        543
 9                         363                        318
 10                        151                        225
 11                        331                        366
 12                        154                        183
 13                        NaN                        NaN
 14                        NaN                        NaN
 15                         16                         21
 16                          7                          7
 17                          9                         14
 18                   0.044077                   0.066038
 19                   0.911846                   1.150943
 20                   0.465257                        0.5
 21                     242815                     249727
 22                      68.57                      69.85
 23                3541.125857                3575.189692
 24                      10800                      10800
 25                       5400                       5400
 26                        NaN                        NaN
 27                     0.0854                     0.0854
 28                       1520                       1565
 29                       4398                       4870
 30                         10                          7
 31                          6                         14
 32                      0.625                   0.333333
 33                          7                          6
 34                       1/16                       1/21
 35                        NaN                        NaN
 36                        NaN                        NaN
 37                        NaN                        NaN
 38                        NaN                        NaN

                    Unnamed: 9  ... Unnamed: 26 Unnamed: 27  \
 0                         NaN  ...         NaN         NaN
 1   CLUB RESIDENCIAL \nJul-23  ...         NaN         NaN
 2                      877297  ...         NaN         NaN
 3                      314431  ...         NaN         NaN
 4                         833  ...         NaN         NaN
 5                        1657  ...         NaN         NaN
 6                    1.989196  ...         NaN         NaN
 7                   75.318182  ...         NaN         NaN
 8                         513  ...         NaN         NaN
 9                         389  ...         NaN         NaN
 10                        124  ...         NaN         NaN
 11                        315  ...         NaN         NaN
 12                        141  ...         NaN         NaN
 13                        NaN  ...         NaN         NaN
 14                        NaN  ...         NaN         NaN
 15                         22  ...         NaN         NaN
 16                          9  ...         NaN         NaN
 17                         13  ...         NaN         NaN
 18                   0.056555  ...         NaN         NaN
 19                   0.809769  ...         NaN         NaN
 20                   0.447619  ...         NaN         NaN
 21                     246882  ...         NaN         NaN
 22                       69.1  ...         NaN         NaN
 23                3572.821997  ...         NaN         NaN
 24                       7300  ...         NaN         NaN
 25                       5400  ...         NaN         NaN
 26                        NaN  ...         NaN         NaN
 27                      0.086  ...         NaN         NaN
 28                       1577  ...         NaN         NaN
 29                       4412  ...         NaN         NaN
 30                          8  ...         NaN         NaN
 31                         14  ...         NaN         NaN
 32                   0.363636  ...         NaN         NaN
 33                          8  ...         NaN         NaN
 34                       4/22  ...         NaN         NaN
 35                        NaN  ...         NaN         NaN
 36                        NaN  ...         NaN         NaN
 37                        NaN  ...         NaN         NaN
 38                        NaN  ...         NaN         NaN

                          Unnamed: 28                             Unnamed: 29  \
 0                                NaN                                     NaN
 1   CLUB RESIDENCIAL \nPromedio 2024  CLUB RESIDENCIAL \nPromedio Ene-Mar 25
 2                     1685339.291667                                 1835857
 3                             673396                                  569733
 4                               1780                                    1102
 5                          2007.9725                                    2068
 6                           1.198542                                1.876588
 7                         126.788349                              110.825295
 8                                537                                  550.33
 9                             307.25                                  323.33
 10                            229.75                                     227
 11                            103.25                                  222.33
 12                                54                                   98.66
 13                              37.5                                   69.66
 14                              16.5                                      29
 15                                16                                   18.66
 16                             13.25                                   12.33
 17                              2.75                                    6.33
 18                          0.052075                                0.057712
 19                          0.336046                                0.687626
 20                          0.523002                                0.443755
 21                          255197.6                               259685.71
 22                         70.707812                                   70.89
 23                       3609.185336                             3663.220624
 24                              7300                                     NaN
 25                              5400                                     NaN
 26                                 -                                     NaN
 27                            0.0904                                     NaN
 28                              1535                                     NaN
 29                              4400                                     NaN
 30                              8.75                                    6.33
 31                              7.25                                   12.33
 32                          0.546875                                0.339228
 33                          6.818182                                     NaN
 34                            50/244                                3.3/18.6
 35                               NaN                                      16
 36                               NaN                                     NaN
 37                               NaN                                     NaN
 38                               NaN                                     NaN

                       Unnamed: 30                       Unnamed: 31  \
 0                             NaN                               NaN
 1   CLUB RESIDENCIAL \nABRIL 2025  CLUB RESIDENCIAL al 26 MAYO 2025
 2                         1548174                           1811016
 3                          761865                            905624
 4                            1466                              1082
 5                            2296                              1728
 6                        1.566166                          1.597043
 7                             164                             172.8
 8                             449                               308
 9                             268                               189
 10                            181                               119
 11                            199                               154
 12                            126                                96
 13                            104                                75
 14                             22                                21
 15                             14                                10
 16                              9                                 7
 17                              5                                 3
 18                       0.052239                           0.05291
 19                       0.742537                          0.814815
 20                       0.633166                          0.623377
 21                         260957                            248570
 22                         75.607                             70.27
 23                    3451.492587                       3537.355913
 24                            NaN                               NaN
 25                            NaN                               NaN
 26                            NaN                               NaN
 27                            NaN                               NaN
 28                            NaN                               NaN
 29                            NaN                               NaN
 30                              7                                 5
 31                              7                                 5
 32                            0.5                               0.5

In [53]:
df_club = dfs['CLUB']
df_club.columns = df_club.iloc[1]
df_club = df_club[2:]#.reset_index()  # Elimina las dos primeras filas
df_club.rename(columns={df_club.columns[0]: 'MÉTRICAS'}, inplace=True)  # Renombra la primera columna
df_club

C:\Users\diego.dinatale\AppData\Local\Temp\ipykernel_23328\3618484017.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_club.rename(columns={df_club.columns[0]: 'MÉTRICAS'}, inplace=True)  # Renombra la primera columna

1,MÉTRICAS,CLUB RESIDENCIAL \nPromedio 2022,CLUB RESIDENCIAL \nPromedio 2023,CLUB RESIDENCIAL \nEne-23,CLUB RESIDENCIAL \nFeb-23,CLUB RESIDENCIAL \nMar-23,CLUB RESIDENCIAL \nAbr-23,CLUB RESIDENCIAL \nMay-23,CLUB RESIDENCIAL \nJun-23,CLUB RESIDENCIAL \nJul-23,...,NaN,NaN,CLUB RESIDENCIAL \nPromedio 2024,CLUB RESIDENCIAL \nPromedio Ene-Mar 25,CLUB RESIDENCIAL \nABRIL 2025,CLUB RESIDENCIAL al 26 MAYO 2025,NaN,MÉTRICAS,MÉTRICAS,MÉTRICAS
2,IMPRESIONES,608459,981611,715768,402966,667358,1229758,743514,722817,877297,...,NaN,NaN,1685339.291667,1835857,1548174,1811016,NaN,NaN,NaN,NaN
3,ALCANCE,255229.5,379498,318835,169664,241497,402449,275879,208739,314431,...,NaN,NaN,673396,569733,761865,905624,NaN,NaN,NaN,NaN
4,LEADS,1813.416667,1329,1509,1308,1441,1011,910,934,833,...,NaN,NaN,1780,1102,1466,1082,NaN,NaN,NaN,NaN
5,INVERSIÓN,1560.788333,"$1,715",1032.6,1229,1687,2305,2260,1547,1657,...,NaN,NaN,2007.9725,2068,2296,1728,NaN,NaN,NaN,NaN
6,COSTO POR LEAD,0.860689,$1.43,0.684294,0.939602,1.170715,2.279921,2.483516,1.656317,1.989196,...,NaN,NaN,1.198542,1.876588,1.566166,1.597043,NaN,NaN,NaN,NaN
7,COSTO DE ADQUISICIÓN,60.030321,$88,46.936364,81.933333,67.48,88.653846,141.25,73.666667,75.318182,...,NaN,NaN,126.788349,110.825295,164,172.8,NaN,NaN,NaN,NaN
8,VISITAS TOTALES,652,481.545455,422,363,405,428,514,543,513,...,NaN,NaN,537,550.33,449,308,NaN,NaN,NaN,NaN
9,VISITAS PRESENCIALES,316,323.818182,374,318,324,310,363,318,389,...,NaN,NaN,307.25,323.33,268,189,NaN,NaN,NaN,NaN
10,VISITAS VIRTUALES,336,157.727273,48,45,81,118,151,225,124,...,NaN,NaN,229.75,227,181,119,NaN,NaN,NaN,NaN
11,EVALUADOS x BCO.,287,232.090909,187,224,248,231,331,366,315,...,NaN,NaN,103.25,222.33,199,154,NaN,NaN,NaN,NaN
12,PRE CALIFICADOS x BCO,157,112.454545,97,113,143,112,154,183,141,...,NaN,NaN,54,98.66,126,96,NaN,NaN,NaN,NaN
13,PRE CALIFICADOS x CH DIRECTO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,37.5,69.66,104,75,NaN,NaN,NaN,NaN
14,PRE CALIFICADOS x PLAN AHORRO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,16.5,29,22,21,NaN,NaN,NaN,NaN
15,SEPARACIONES BRUTAS TOTALES,26,20.818182,22,15,25,26,16,21,22,...,NaN,NaN,16,18.66,14,10,NaN,Motivo de no compra pre calificados - Mayo,Cant.,%
16,SEPARACIONES CH DIRECTO O CONTADO,NaN,10.636364,14,11,15,17,7,7,9,...,NaN,NaN,13.25,12.33,9,7,NaN,Mal reportado,1,0.008333
17,SEPARACIONES PLAN AHORRO,NaN,10.181818,8,4,10,9,9,14,13,...,NaN,NaN,2.75,6.33,5,3,NaN,Sólo información,55,0.458333
18,% Penetración VIVA SB/Visitas Presenciales,0.082278,0.06429,0.058824,0.04717,0.07716,0.083871,0.044077,0.066038,0.056555,...,NaN,NaN,0.052075,0.057712,0.052239,0.05291,NaN,Evaluando,64,0.533333
19,% Atenciones Banco/Visitas Presenciales,0.908228,0.716732,0.5,0.704403,0.765432,0.745161,0.911846,1.150943,0.809769,...,NaN,NaN,0.336046,0.687626,0.742537,0.814815,NaN,Total,120,1
20,% Penetración Banco PreCalificados/Evaluados,0.547038,0.484528,0.518717,0.504464,0.576613,0.484848,0.465257,0.5,0.447619,...,NaN,NaN,0.523002,0.443755,0.633166,0.623377,NaN,NaN,NaN,NaN
21,Precio Promedio Vendido,245628,243391,232131,236530,236317,242481,242815,249727,246882,...,NaN,NaN,255197.6,259685.71,260957,248570,NaN,NaN,NaN,NaN
22,Metraje Promedio (Dpto. Tipico),73,69.1,69.68,68.62,71.97,69.56,68.57,69.85,69.1,...,NaN,NaN,70.707812,70.89,75.607,70.27,NaN,NaN,NaN,NaN
23,Precio Promedio Vendido m2 (Dpto. típico),3364.767123,3522.301013,3331.386338,3446.954241,3283.548701,3485.925819,3541.125857,3575.189692,3572.821997,...,NaN,NaN,3609.185336,3663.220624,3451.492587,3537.355913,NaN,NaN,NaN,NaN
24,BBP,10800,7300,10800,10800,10800,10800,10800,10800,7300,...,NaN,NaN,7300,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,BMS,5400,5400,5400,5400,5400,5400,5400,5400,5400,...,NaN,NaN,5400,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Bono Integrador,-,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,RangoTasa Minima p/Cálculo,0.0882,0.0904,0.0937,0.086,0.0879,0.0854,0.0854,0.0854,0.086,...,NaN,NaN,0.0904,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,"Cuota (dobles, 300 meses)",1567,1535,1447,1485,1505,1517,1520,1565,1577,...,NaN,NaN,1535,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Ingreso Bruto Requerido (0.7),4398,4400,4087,4254,4286,4365,4398,4870,4412,...,NaN,NaN,4400,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Caídas,10,8.454545,8,1,18,10,10,7,8,...,NaN,NaN,8.75,6.33,7,5,NaN,NaN,NaN,NaN
31,SEPARACIONES NETAS TOTALES,16,12.363636,14,14,7,16,6,14,14,...,NaN,NaN,7.25,12.33,7,5,NaN,NaN,NaN,NaN
32,% Caídas,0.384615,0.406114,0.363636,0.066667,0.72,0.384615,0.625,0.333333,0.363636,...,NaN,NaN,0.546875,0.339228,0.5,0.5,NaN,NaN,NaN,NaN
33,Visitas que migraron y reservaron en otro proy...,14,6.818182,4,8,15,9,7,6,8,...,NaN,NaN,6.818182,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Relación entre Dptos vendidos c/estac.,114/316,50/244,5/22,5/15,6/25,5/26,1/16,1/21,4/22,...,NaN,NaN,50/244,3.3/18.6,5/14,3/10,NaN,NaN,NaN,NaN
35,Stock de Departamentos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,16,154,148,NaN,NaN,NaN,NaN
36,Stock Estacionamientos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN